[package]
name = "tinix"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = {version = "0.9.8", features = ["map_physical_memory"]}
x86_64 = "0.14.3"
bit_field = "0.10.1"
spin = {version = "0.9.0", default-features = false}
volatile = "*"
